---
default:
  image: 'python:3'
  before_script:
    - pip install tox

stages:
  - build
  - test
  - deploy

lint:
  stage: build
  script:
    - tox -e gitlint
    - tox
  except:
    - gh-pages

test:
  stage: test
  script:
    - tox -e build
    - tox -e check
  except:
    - gh-pages

update-gh-pages:
  stage: deploy
  variables:
    GIT_COMMITTER_NAME: "$GITLAB_USER_NAME"
    GIT_COMMITTER_EMAIL: "$GITLAB_USER_EMAIL"
    DOCS_DEPLOY_BRANCH: "$CI_COMMIT_BRANCH"
  script:
    - git fetch origin gh-pages
    - tox -e mike -- --push
  only:
    - main
    - kna1
    - sto2
    - fra1
    - sto1hs
    - sto2hs
    - sto-com

.pages:
  stage: deploy
  script:
    - tox -e deploy-gitlab
  artifacts:
    paths:
      - public

pages:
  extends: .pages
  pages:
    path_prefix: "$CI_COMMIT_BRANCH"
    expire_in: 4 weeks
  except:
    - main
    - gh-pages

gh-pages:
  stage: deploy
  extends: .pages
  script:
    - mkdir public
    - mv * public
  only:
    - gh-pages
